BartoszCichecki/LenovoLegionToolkit

- LenovoLegionToolkit.WPF/Windows/Utils/NotificationWindow.cs
This fixes the white flicker when the notification window appears.
> Set NotificationWindow WindowStyle to None

- LenovoLegionToolkit.Lib/Features/AbstractLenovoGamezoneWmiFeature.cs
- LenovoLegionToolkit.Lib/Features/IGPUModeFeature.cs
- LenovoLegionToolkit.WPF/Windows/MainWindow.xaml.cs
- README.md
Hi! 
Thank you for building this useful tool! Now I may run away from the burden Vantage Service and enjoy a cool laptop. 
This is a fix regarding issue #236, and I have only tested on my laptop. There is no exception handling regarding the introduced WMI method, so this pull request is just for reference (To provide a working sample for Legion 7i Gen 7).
> Quick fix for issue #236

- README_zh-hans.md
> Update translation credits.

- LenovoLegionToolkit.Lib/Controllers/GodModeController.cs
- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
- LenovoLegionToolkit.WPF/Windows/Dashboard/GodModeSettingsWindow.xaml.cs
> HACN Support

- LenovoLegionToolkit.Lib.Automation/Listeners/ProcessAutomationListener.cs
- LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/ProcessesAreRunningAutomationPipelineTrigger.cs
- LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/ProcessesStopRunningAutomationPipelineTrigger.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.WPF/Extensions/ImageSourceExtensions.cs
> Fallback to process ID for restricted processes

- LenovoLegionToolkit.Lib.Automation/AutomationProcessor.cs
- LenovoLegionToolkit.Lib.Automation/Pipeline/AutomationPipeline.cs
- LenovoLegionToolkit.Lib/Settings/AbstractSettings.cs
- LenovoLegionToolkit.Lib/Settings/ApplicationSettings.cs
- LenovoLegionToolkit.WPF/App.xaml.cs
- LenovoLegionToolkit.WPF/Extensions/ComboBoxExtensions.cs
- LenovoLegionToolkit.WPF/Pages/SettingsPage.xaml
- LenovoLegionToolkit.WPF/Pages/SettingsPage.xaml.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Windows/MainWindow.xaml.cs
> Fn+F9 actions

- LenovoLegionToolkit.Lib/Enums.cs
- LenovoLegionToolkit.Lib/Settings/ApplicationSettings.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Resources/Resource.ro.resx
- LenovoLegionToolkit.WPF/Utils/NotificationsManager.cs
- LenovoLegionToolkit.WPF/Windows/MainWindow.xaml.cs
- LenovoLegionToolkit.WPF/Windows/Settings/NotificationsSettingsWindow.xaml
- LenovoLegionToolkit.WPF/Windows/Settings/NotificationsSettingsWindow.xaml.cs
> Show notifications for smart key

- LenovoLegionToolkit.Lib/Controllers/SpectrumKeyboardBacklightController.cs
- LenovoLegionToolkit.Lib/Native.cs
- LenovoLegionToolkit.WPF/App.xaml.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/SpectrumKeyboardBacklightControl.xaml.cs
- LenovoLegionToolkit.WPF/Controls/Settings/CPUBoostModeControl.xaml
- LenovoLegionToolkit.WPF/IoCModule.cs
- LenovoLegionToolkit.WPF/Pages/PackagesPage.xaml
- LenovoLegionToolkit.WPF/Pages/SettingsPage.xaml
- LenovoLegionToolkit.WPF/Pages/SettingsPage.xaml.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Utils/SpectrumScreenCapture.cs
- LenovoLegionToolkit.WPF/Windows/KeyboardBacklight/Spectrum/SpectrumKeyboardBacklightEditEffectWindow.xaml
- LenovoLegionToolkit.WPF/Windows/KeyboardBacklight/Spectrum/SpectrumKeyboardBacklightEditEffectWindow.xaml.cs
- LenovoLegionToolkit.WPF/Windows/Settings/PowerPlansWindow.xaml
> Aurora Sync

- LenovoLegionToolkit.Lib/Enums.cs
- LenovoLegionToolkit.Lib/Resources/Resource.Designer.cs
- LenovoLegionToolkit.Lib/Resources/Resource.resx
- LenovoLegionToolkit.Lib/Resources/Resource.ro.resx
- LenovoLegionToolkit.Lib/Settings/ApplicationSettings.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Resources/Resource.ro.resx
- LenovoLegionToolkit.WPF/Utils/NotificationsManager.cs
- LenovoLegionToolkit.WPF/Windows/Settings/NotificationsSettingsWindow.xaml
- LenovoLegionToolkit.WPF/Windows/Settings/NotificationsSettingsWindow.xaml.cs
- LenovoLegionToolkit.WPF/Windows/Utils/NotificationWindow.cs
> Add option to change notification position

- LenovoLegionToolkit.Lib/Listeners/SpecialKeyListener.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Windows/Settings/ExcludeRefreshRatesWindow.xaml
- LenovoLegionToolkit.WPF/Windows/Settings/ExcludeRefreshRatesWindow.xaml.cs
- Clarify "Exclude refresh rates" option
- Keep unavailable refresh rates when excluding
> Clarify "Exclude refresh rates" option

- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
> Enable custom mode for KFCN >32

- LenovoLegionToolkit.Lib/Features/BatteryFeature.cs
- LenovoLegionToolkit.Lib/Features/IGPUModeFeature.cs
- LenovoLegionToolkit.Lib/Listeners/NativeWindowsMessageListener.cs
- LenovoLegionToolkit.Lib/Listeners/PowerStateListener.cs
- LenovoLegionToolkit.Lib/System/FnKeys.cs
- LenovoLegionToolkit.Lib/System/Registry.cs
- LenovoLegionToolkit.WPF/App.xaml.cs
> Restore battery charge mode

- LenovoLegionToolkit.Lib/Controllers/GodModeController.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.WPF/Controls/FanCurveControl.xaml.cs
- LenovoLegionToolkit.WPF/Windows/Dashboard/GodModeSettingsWindow.xaml
- LenovoLegionToolkit.WPF/Windows/Dashboard/GodModeSettingsWindow.xaml.cs
> Zero RPM Custom Mode

- LenovoLegionToolkit.Lib/Utils/UpdateChecker.cs
Spelling correction: update variable timeSpaneSinceLastUpdate to timeSpanSinceLastUpdate.
> Minor spelling correction in UpdateChecker.cs

- LenovoLegionToolkit.Lib/Controllers/SpectrumKeyboardBacklightController.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/SpectrumDeviceControl.xaml
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/SpectrumDeviceControl.xaml.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/SpectrumKeyboardBacklightControl.xaml.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/SpectrumKeyboardButtonControl.xaml.cs
Check for key visibility based on keycode.
> Make Spectrum more dynamic

- LenovoLegionToolkit.Lib.Automation/Utils/AutomationSettings.cs
- LenovoLegionToolkit.Lib/Controllers/GodModeController.cs
- LenovoLegionToolkit.Lib/Extensions/DictionaryExtensions.cs
- LenovoLegionToolkit.Lib/Features/PowerModeFeature.cs
- LenovoLegionToolkit.Lib/Settings/AbstractSettings.cs
- LenovoLegionToolkit.Lib/Settings/ApplicationSettings.cs
- LenovoLegionToolkit.Lib/Settings/BalanceModeSettings.cs
- LenovoLegionToolkit.Lib/Settings/GodModeSettings.cs
- LenovoLegionToolkit.Lib/Settings/PackageDownloaderSettings.cs
- LenovoLegionToolkit.Lib/Settings/RGBKeyboardSettings.cs
- LenovoLegionToolkit.Lib/Settings/SpectrumKeyboardSettings.cs
- LenovoLegionToolkit.Lib/Settings/SunriseSunsetSettings.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.WPF/Extensions/ComboBoxExtensions.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Windows/Dashboard/GodModeSettingsWindow.xaml
- LenovoLegionToolkit.WPF/Windows/Dashboard/GodModeSettingsWindow.xaml.cs
> Custom Mode Presets

- LenovoLegionToolkit.Lib/Controllers/CPUBoostController.cs
- LenovoLegionToolkit.Lib/IoCModule.cs
- LenovoLegionToolkit.Lib/Listeners/DisplayBrightnessListener.cs
- LenovoLegionToolkit.Lib/Settings/ApplicationSettings.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.Lib/Utils/ThrottleLastDispatcher.cs
- LenovoLegionToolkit.WPF/Pages/SettingsPage.xaml
- LenovoLegionToolkit.WPF/Pages/SettingsPage.xaml.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
> Single Display Brightness

- LenovoLegionToolkit.Lib/Controllers/GodModeController.cs
- LenovoLegionToolkit.Lib/Settings/GodModeSettings.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.WPF/Controls/Dashboard/GodMode/GodModeSliderControl.xaml
- LenovoLegionToolkit.WPF/Controls/Dashboard/GodMode/GodModeSliderControl.xaml.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Windows/Dashboard/GodModeSettingsWindow.xaml
- LenovoLegionToolkit.WPF/Windows/Dashboard/GodModeSettingsWindow.xaml.cs
> Custom Mode polish

- LenovoLegionToolkit.Lib.Automation/Pipeline/AutomationPipeline.cs
- LenovoLegionToolkit.Lib/Utils/ThrottleFirstDispatcher.cs
- LenovoLegionToolkit.Lib/Utils/ThrottleLastDispatcher.cs
- LenovoLegionToolkit.WPF/Controls/Automation/Pipeline/AutomationPipelineControl.cs
- LenovoLegionToolkit.WPF/Pages/AutomationPage.xaml.cs
- LenovoLegionToolkit.WPF/Pages/PackagesPage.xaml
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.ar.resx
- LenovoLegionToolkit.WPF/Resources/Resource.bs.resx
- LenovoLegionToolkit.WPF/Resources/Resource.cs.resx
- LenovoLegionToolkit.WPF/Resources/Resource.de.resx
- LenovoLegionToolkit.WPF/Resources/Resource.el.resx
- LenovoLegionToolkit.WPF/Resources/Resource.es.resx
- LenovoLegionToolkit.WPF/Resources/Resource.fr.resx
- LenovoLegionToolkit.WPF/Resources/Resource.it.resx
- LenovoLegionToolkit.WPF/Resources/Resource.nl-nl.resx
- LenovoLegionToolkit.WPF/Resources/Resource.pt-br.resx
- LenovoLegionToolkit.WPF/Resources/Resource.pt.resx
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Resources/Resource.ro.resx
- LenovoLegionToolkit.WPF/Resources/Resource.ru.resx
- LenovoLegionToolkit.WPF/Resources/Resource.sk.resx
- LenovoLegionToolkit.WPF/Resources/Resource.tr.resx
- LenovoLegionToolkit.WPF/Resources/Resource.uk.resx
- LenovoLegionToolkit.WPF/Resources/Resource.vi.resx
- LenovoLegionToolkit.WPF/Resources/Resource.zh-hans.resx
- LenovoLegionToolkit.WPF/Utils/ContextMenuHelper.cs
- LenovoLegionToolkit.WPF/Windows/Utils/SymbolRegularPicker.xaml
- LenovoLegionToolkit.WPF/Windows/Utils/SymbolRegularPicker.xaml.cs
> Icon picker for Quick Actions

- LenovoLegionToolkit.Lib/Features/PowerModeFeature.cs
- LenovoLegionToolkit.Lib/Listeners/ThermalModeListener.cs
- LenovoLegionToolkit.Lib/Utils/ThreadSafeCounter.cs
> Custom Mode switch bug on Gen 6.

- LenovoLegionToolkit.Lib/Controllers/GodMode/AbstractGodModeController.cs
- LenovoLegionToolkit.Lib/Controllers/GodMode/GodModeController.cs
- LenovoLegionToolkit.Lib/Controllers/GodMode/GodModeControllerV1.cs
- LenovoLegionToolkit.Lib/Controllers/GodMode/GodModeControllerV2.cs
- LenovoLegionToolkit.Lib/Controllers/GodMode/IGodModeController.cs
- LenovoLegionToolkit.Lib/Features/PowerModeFeature.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
> PL restoration

- LenovoLegionToolkit.Lib/Features/PowerModeFeature.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
> Toggle through Quiet

- LenovoLegionToolkit.Lib/Features/PowerModeFeature.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
> Cycle through other power modes to restore PLs

- LenovoLegionToolkit.WPF/Controls/StatusTrayPopup.xaml.cs
- LenovoLegionToolkit.WPF/Windows/MainWindow.xaml.cs
> Popup crash

- LenovoLegionToolkit.Lib/Controllers/SpectrumKeyboardBacklightController.cs
- LenovoLegionToolkit.Lib/Extensions/SpectrumKeyboardBacklightEffectTypeExtensions.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/Device/SpectrumDeviceControl.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/SpectrumKeyboardBacklightControl.xaml.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/SpectrumKeyboardEffectControl.xaml.cs
- LenovoLegionToolkit.WPF/Windows/KeyboardBacklight/Spectrum/SpectrumKeyboardBacklightEditEffectWindow.xaml.cs
> Separate all light effects from whole keyboard effects

- LenovoLegionToolkit.WPF/Pages/AboutPage.xaml.cs
- LenovoLegionToolkit.WPF/Pages/PackagesPage.xaml.cs
- LenovoLegionToolkit.WPF/Windows/MainWindow.xaml.cs
- LenovoLegionToolkit.WPF/Windows/Utils/UnsupportedWindow.xaml.cs
> Fix open folder crash

- LenovoLegionToolkit.Lib/Controllers/GodMode/AbstractGodModeController.cs
- LenovoLegionToolkit.Lib/Controllers/GodMode/GodModeController.cs
- LenovoLegionToolkit.Lib/Controllers/GodMode/GodModeControllerV1.cs
- LenovoLegionToolkit.Lib/Controllers/GodMode/GodModeControllerV2.cs
- LenovoLegionToolkit.Lib/Controllers/GodMode/IGodModeController.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.WPF/Controls/Dashboard/PowerModeControl.cs
- LenovoLegionToolkit.WPF/Controls/FanCurveControl.xaml.cs
- LenovoLegionToolkit.WPF/Windows/Dashboard/GodModeSettingsWindow.xaml.cs
> Remove 0RPM mode for gen8 devices

- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
- README.md
> Enabled custom mode foro M3CN32WW and higher BIOS.

- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Windows/Automation/CreateAutomationPipelineWindow.xaml.cs
Made the "Multiple triggers..." display name localizable.
> Multiple triggers display name is now localizable.

- LenovoLegionToolkit.Lib/Features/AbstractLenovoLightingFeature.cs
- LenovoLegionToolkit.Lib/Features/PanelLogoBacklightFeature.cs
- LenovoLegionToolkit.Lib/Features/PanelLogoLenovoLightingBacklightFeature.cs
- LenovoLegionToolkit.Lib/Features/PortsBacklightFeature.cs
- LenovoLegionToolkit.Lib/Features/WhiteKeyboardBacklightFeature.cs
- LenovoLegionToolkit.Lib/Features/WhiteKeyboardDriverBacklightFeature.cs
- LenovoLegionToolkit.Lib/Features/WhiteKeyboardLenovoLightingBacklightFeature.cs
- LenovoLegionToolkit.Lib/IoCModule.cs
- LenovoLegionToolkit.Lib/PackageDownloader/Detectors/Rules/BiosPackageRule.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
- LenovoLegionToolkit.WPF/App.xaml.cs
- LenovoLegionToolkit.WPF/Flags.cs
- LenovoLegionToolkit.sln.DotSettings
> Improved white keyboard control and disable lenovo lighting flag

- LenovoLegionToolkit.Lib/Features/PanelLogoBacklightFeature.cs
- LenovoLegionToolkit.Lib/Features/WhiteKeyboardBacklightFeature.cs
> Hide white keyboard backlight control if RGB or Spectrum is detected.

- LenovoLegionToolkit.Lib/Controllers/DisplayBrightnessController.cs
- LenovoLegionToolkit.Lib/Controllers/GodMode/GodModeControllerV1.cs
- LenovoLegionToolkit.Lib/Controllers/GodMode/GodModeControllerV2.cs
- LenovoLegionToolkit.Lib/Controllers/Sensors/AbstractSensorsController.cs
- LenovoLegionToolkit.Lib/Controllers/Sensors/SensorsControllerV3.cs
- LenovoLegionToolkit.Lib/Enums.cs
- LenovoLegionToolkit.Lib/Features/AbstractLenovoGamezoneWmiFeature.cs
- LenovoLegionToolkit.Lib/Features/Hybrid/IGPUModeCapabilityFeature.cs
- LenovoLegionToolkit.Lib/Features/Hybrid/IGPUModeFeature.cs
- LenovoLegionToolkit.Lib/Features/InstantBoot/InstantBootCapabilityFeature.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
- LenovoLegionToolkit.WPF/Controls/Dashboard/SensorsControl.xaml
> Fix Gen 8 temperature reading

- LenovoLegionToolkit.Lib/Enums.cs
- LenovoLegionToolkit.Lib/Features/FlipToStart/FlipToStartCapabilityFeature.cs
- LenovoLegionToolkit.Lib/Features/FlipToStart/FlipToStartFeature.cs
- LenovoLegionToolkit.Lib/Features/FlipToStart/FlipToStartUEFIFeature.cs
- LenovoLegionToolkit.Lib/IoCModule.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
> [Experimental] Flip to start

- LenovoLegionToolkit.WPF/Controls/ColorPickerControl.xaml.cs
> Fix crash caused by inputting non-digit into color picker input.

- LenovoLegionToolkit.WPF/Windows/Dashboard/GodModeSettingsWindow.xaml
- LenovoLegionToolkit.WPF/Windows/Dashboard/GodModeSettingsWindow.xaml.cs
> Temporarily detach value listeners.

- README.md
Fixes README.md's first two FAQ links, fixes NVIDIA capitalization, and corrects punctuation in `faq-gpu-oc`'s title.
> NVIDIA capitalization and vantage-running + virus FAQ

- README.md
> Update download instructions in README

- LenovoLegionToolkit.Lib/Features/Hybrid/HybridModeFeature.cs
- LenovoLegionToolkit.Lib/Features/Hybrid/Notify/AbstractDGPUNotify.cs
- LenovoLegionToolkit.Lib/Features/Hybrid/Notify/DGPUNotify.cs
- LenovoLegionToolkit.Lib/Features/Hybrid/Notify/IDGPUNotify.cs
- LenovoLegionToolkit.WPF/App.xaml.cs
> Help dGPU eject in Hybrid iGPU-only mode on boot

- LenovoLegionToolkit.Lib/Controllers/Sensors/AbstractSensorsController.cs
- LenovoLegionToolkit.Lib/Controllers/Sensors/ISensorsController.cs
- LenovoLegionToolkit.Lib/Controllers/Sensors/SensorsController.cs
- LenovoLegionToolkit.Lib/Utils/SafePerformanceCounter.cs
- LenovoLegionToolkit.WPF/Controls/Dashboard/SensorsControl.xaml.cs
> Reset performance counters before use

- LenovoLegionToolkit.Lib/Controllers/GodMode/AbstractGodModeController.cs
- LenovoLegionToolkit.WPF/Controls/Dashboard/GodMode/GodModeValueControl.xaml.cs
> Adjust code to show ComboBoxes in correct places

- LenovoLegionToolkit.Lib.Automation/AutomationEnvironment.cs
- LenovoLegionToolkit.Lib.Automation/AutomationProcessor.cs
- LenovoLegionToolkit.Lib.Automation/IAutomationEvent.cs
- LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/IAutomationPipelineTrigger.cs
- LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/UserInactivityAutomationPipelineTrigger.cs
- LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/WiFiConnectedAutomationPipelineTrigger.cs
- LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/WiFiDisconnectedAutomationPipelineTrigger.cs
- LenovoLegionToolkit.Lib/AutoListeners/WiFiAutoListener.cs
- LenovoLegionToolkit.Lib/IoCModule.cs
- LenovoLegionToolkit.Lib/Listeners/WifiListener.cs
- LenovoLegionToolkit.Lib/NativeMethods.txt
- LenovoLegionToolkit.Lib/System/WiFi.cs
- LenovoLegionToolkit.WPF/Controls/Automation/AutomationPipelineControl.cs
- LenovoLegionToolkit.WPF/Extensions/AutomationPipelineTriggerExtensions.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Windows/Automation/AutomationPipelineTriggerConfigurationWindow.xaml.cs
- LenovoLegionToolkit.WPF/Windows/Automation/CreateAutomationPipelineWindow.xaml.cs
- LenovoLegionToolkit.WPF/Windows/Automation/TabItemContent/UserInactivityPipelineTriggerTabItemContent.xaml.cs
- LenovoLegionToolkit.WPF/Windows/Automation/TabItemContent/WiFiConnectedPipelineTriggerTabItemContent.xaml
- LenovoLegionToolkit.WPF/Windows/Automation/TabItemContent/WiFiConnectedPipelineTriggerTabItemContent.xaml.cs
> WiFi connected/disconnected actions

- README_zh-hans.md
The Chinese (simplified) README is extremely outdated.
I translated the texts which are new in the README and don't appear in the Chinese one, and did a group of tiny changes to the old translated texts in order to change them into written-language.
> Update Chinese README

- LenovoLegionToolkit.Lib/Enums.cs
- LenovoLegionToolkit.Lib/Listeners/DriverKeyListener.cs
- LenovoLegionToolkit.Lib/Listeners/SpecialKeyListener.cs
- LenovoLegionToolkit.Lib/System/AirplaneMode.cs
> Added new SpecialKey values for Gen 9

- LenovoLegionToolkit.Lib/Controllers/SpectrumKeyboardBacklightController.cs
- LenovoLegionToolkit.Lib/Enums.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/Device/SpectrumDeviceControl.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/Device/SpectrumDeviceFullAlternativeControl.xaml
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/Device/SpectrumDeviceFullAlternativeControl.xaml.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/Device/SpectrumZoneControl.xaml.cs
> Added Spectrum layout for Legion 9

- LenovoLegionToolkit.Lib/Controllers/SpectrumKeyboardBacklightController.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/Spectrum/SpectrumKeyboardBacklightControl.xaml.cs
> Optimize Spectrum refresh

- LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/ExternalDisplayConnectedAutomationPipelineTrigger.cs
- LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/ExternalDisplayDisconnectedAutomationPipelineTrigger.cs
- LenovoLegionToolkit.Lib/AutoListeners/WiFiAutoListener.cs
- LenovoLegionToolkit.Lib/Controllers/WindowsPowerModeController.cs
- LenovoLegionToolkit.Lib/Controllers/WindowsPowerPlanController.cs
- LenovoLegionToolkit.Lib/Enums.cs
- LenovoLegionToolkit.Lib/Listeners/NativeWindowsMessageListener.cs
- LenovoLegionToolkit.Lib/System/ExternalDisplays.cs
- LenovoLegionToolkit.Lib/System/InternalDisplay.cs
> Distinguish between internal and external monitors connected

- LenovoLegionToolkit.Lib/Controllers/RGBKeyboardBacklightController.cs
- LenovoLegionToolkit.Lib/Controllers/SpectrumKeyboardBacklightController.cs
- LenovoLegionToolkit.Lib/Enums.cs
- LenovoLegionToolkit.Lib/Extensions/RGBKeyboardBacklightPresetExtensions.cs
- LenovoLegionToolkit.Lib/Resources/Resource.Designer.cs
- LenovoLegionToolkit.Lib/Resources/Resource.resx
- LenovoLegionToolkit.Lib/Settings/RGBKeyboardSettings.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/RGB/RGBKeyboardBacklightControl.xaml
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/RGB/RGBKeyboardBacklightControl.xaml.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
> Add 4th preset to 4 zone RGB keyboard

- LenovoLegionToolkit.WPF/Pages/SettingsPage.xaml.cs
> Fix typo in CLI PATH setting

- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
Fix: #1438.
One possible fix for the issue, simply change the texts in `WinKeyAutomationStepControl_Title` and `WinKeyAutomationStepControl_Message`, no other changes would be needed.
> Fix WinKeyAutomationStepControl description

- LenovoLegionToolkit.WPF/CLI/IpcServer.cs
Fixes #1491 
Fix typo to call correct controller
> Call correct controller for get RGB preset CLI command

- LenovoLegionToolkit.Lib.Automation/AutomationProcessor.cs
- LenovoLegionToolkit.Lib.Automation/Pipeline/AutomationPipeline.cs
- LenovoLegionToolkit.Lib.Automation/Steps/QuickActionAutomationStep.cs
- LenovoLegionToolkit.WPF/Controls/Automation/Steps/QuickActionAutomationStepControl.cs
> Flatten list of steps

- LenovoLegionToolkit.Lib.Automation/AutomationProcessor.cs
- LenovoLegionToolkit.WPF/Utils/SmartKeyHelper.cs
> Fix Actions freeze when SmartKey is used
