BartoszCichecki/LenovoLegionToolkit

- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
Tested and everything works as expected since Ideapad Gaming 3 is a Legion 5 without the Mux Switch and the advanced cooling system.
> Added support for Ideapad Gaming 3

- LenovoLegionToolkit.WPF/Pages/BatteryPage.xaml.cs
When the discharge rate is positive (battery is charging) show the '+' sign to avoid confusion.
> Show '+' sign when discharge rate is positive

- LenovoLegionToolkit.Lib/Enums.cs
- LenovoLegionToolkit.Lib/Listeners/SpecialKeyListener.cs
On my Legion 5 2021 (which usually only lists 165hz in the display settings, but 60hz can be added with CRU), pressing Fn+R sends the PressTypeDataVal `0x0041002A`.
Some community testing may be needed to see if this value is applicable to other similar laptops.
> Add handling for a different Fn+R key value

- LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/ACAdapterConnectedAutomationPipelineTrigger.cs
- LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/ACAdapterDisconnectedAutomationPipelineTrigger.cs
Should've been `(automationEvent is not PowerAutomationEvent && automationEvent is not StartupAutomationEvent)`, but there's an even nicer way of checking it.
> Fix ACAdapter triggers

- LenovoLegionToolkit.Lib/Controllers/RGBKeyboardBacklightController.cs
- LenovoLegionToolkit.Lib/IoCModule.cs
- LenovoLegionToolkit.Lib/Listeners/SystemThemeListener.cs
- LenovoLegionToolkit.Lib/Settings/ApplicationSettings.cs
- LenovoLegionToolkit.Lib/Settings/RGBKeyboardSettings.cs
- LenovoLegionToolkit.Lib/Settings/RGBKeyboardSettingsZoneConverter.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.Lib/System/SystemTheme.cs
- LenovoLegionToolkit.WPF/Controls/ColorCardControl.cs
- LenovoLegionToolkit.WPF/Controls/ColorCardSystemAwareControl.cs
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/RGBKeyboardBacklightControl.xaml
- LenovoLegionToolkit.WPF/Controls/KeyboardBacklight/RGBKeyboardBacklightControl.xaml.cs
- LenovoLegionToolkit.WPF/Pages/SettingsPage.xaml
- LenovoLegionToolkit.WPF/Pages/SettingsPage.xaml.cs
- LenovoLegionToolkit.WPF/Utils/ThemeManager.cs
This adds the option to match both the app accent color and/or keyboard lightning zones to the system color.
> Match system accent color & minor fixes

- LenovoLegionToolkit.Lib/Features/PowerModeFeature.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.Lib/Utils/Compatibility.cs
Enabling Performance made in the app doesn't update the dGPU temp limit as this is previously set by the Balance mode when pressing FN + R.
> Switch to Balance mode before switching to Performance

- LenovoLegionToolkit.WPF/Resources/Resource.resx
There are some occurrences of "it's" in the English string resources which should be written as "its" instead.
> Use the proper form of "its" in English Resx

- LenovoLegionToolkit.Lib/Utils/WarrantyChecker.cs
See [issue 524](https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/524) and my comment there.
> Warranty status will now be properly displayed if the warranty expires while the app is open

- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Windows/Settings/BootLogoWindow.xaml
- LenovoLegionToolkit.WPF/Windows/Settings/BootLogoWindow.xaml.cs
Link: #1106 
I added a new TextBlock under `_descriptionTextBlock` to hold the messages.
```xaml
<TextBlock
x:Name="_resultTextBlock"
Grid.Row="1"
Grid.Column="0"
Grid.ColumnSpan="2"
Margin="0,82,0,0"
TextWrapping="Wrap">
<TextBlock.Style>
<Style  TargetType="TextBlock">
<Setter Property="Foreground" Value="Red" />
<Style.Triggers>
<Trigger Property="Text" Value="{x:Static resources:Resource.BootLogoWindow_SetCustomSuccess}">
<Setter Property="Foreground" Value="Green" />
</Trigger>
<Trigger Property="Text" Value="{x:Static resources:Resource.BootLogoWindow_SetDefaultSuccess}">
<Setter Property="Foreground" Value="Green" />
</Trigger>
</Style.Triggers>
</Style>
</TextBlock.Style>
</TextBlock>
```
Here I use Trigger to set foreground color. Normally it's set as `Red`, and when the message …
> Show error messages when failing to set / reset custom boot logo

- LenovoLegionToolkit.Lib.Automation/AutomationProcessor.cs
- LenovoLegionToolkit.Lib.Automation/LenovoLegionToolkit.Lib.Automation.csproj
- LenovoLegionToolkit.Lib/AutoListeners/AbstractAutoListener.cs
- LenovoLegionToolkit.Lib/Controllers/AIController.cs
- LenovoLegionToolkit.Lib/Controllers/GPUController.cs
- LenovoLegionToolkit.Lib/Controllers/RGBKeyboardBacklightController.cs
- LenovoLegionToolkit.Lib/Controllers/SmartFnLockController.cs
- LenovoLegionToolkit.Lib/Controllers/SpectrumKeyboardBacklightController.cs
- LenovoLegionToolkit.Lib/LenovoLegionToolkit.Lib.csproj
- LenovoLegionToolkit.Lib/Utils/ThrottleFirstDispatcher.cs
- LenovoLegionToolkit.Lib/Utils/UpdateChecker.cs
- LenovoLegionToolkit.WPF/Pages/AboutPage.xaml
Disclaimer: I am the author of the new library.
Public benchmarks running on GitHub show AsyncNonKeyedLocker to be considerably more performant; in tests NeoSmart.AsyncLock took 9.71x the time and allocated 7.42x the memory.
https://github.com/MarkCiliaVincenti/AsyncNonKeyedLockBenchmarks/actions/runs/7526873065/job/20485876144
> Switched to a more performant locking library

- README.md
- README_zh-hans.md
Translate new texts added with 2.23.0 release.
Small fix: sth like `<name>` (without marking as code) would be treated as a tag in markdown and won't be shown. Therefore they shoule be marked in order to be shown correctly.
> Update Chinese README

- LenovoLegionToolkit.Lib/Utils/Folders.cs
Fixes #1368.
Use `AppDomain.CurrentDomain` property to get program path. Fixed path under `AppData` doesn't work on custom installation.
Besides, I think there's no need to create the program directory before getting it. The installation directory must exist otherwise llt shouldn't be there, therefore I removed the directory create line.
> Get right install dir on custom installation

- LenovoLegionToolkit.Lib/Controllers/GPUController.cs
- LenovoLegionToolkit.Lib/Controllers/Sensors/AbstractSensorsController.cs
Closes: #1501.
Add a `Started` state to `GPUController`. Check the state before getting GPU info to make sure datas would be got successfully.
> Check GPUController is started before getting GPU info

- .github/workflows/build.yml
- .github/workflows/release.yml
Upgrade upload-artifact to v4 since v3 of the artifact actions have been deprecated since Jan 30th, 2025.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Upgrade upload-artifact workflow

- LenovoLegionToolkit.Lib.Automation/Steps/QuickActionAutomationStep.cs
- LenovoLegionToolkit.WPF/Controls/Automation/AutomationPipelineControl.cs
- LenovoLegionToolkit.WPF/Controls/Automation/Steps/QuickActionAutomationStepControl.cs
- LenovoLegionToolkit.WPF/Pages/AutomationPage.xaml.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
Closes: #1574.
Add `QuickActionAutomationStep` to allow users to run a saved quick action pipeline within an automation pipeline. This automation step is only available in automation actions, because referencing a quick action in one another doesn't really make sense, and it may cause problem when we run one quick action in itself. I don't see a simple way to tell automation steps to remove a certain quick action from the list in current architecture, so I removed this feature.
TODO:
Plus: after giving another thought, showing a warning msg when removing referenced quick actions is a bit too more complicated than this PR should be. I'll remove this plan for now, but if you think it's necessary, plz let me know and I'll give another try.
> Quick Action as Automation Step

- LenovoLegionToolkit.WPF/Windows/Utils/NotificationWindow.cs
Fix: #1607.
Add `SWP_NOACTIVATE` flag when calling `SetWindowPos` API to keep OSD window focusless.
> Keep OSD Window No_Activated State on moving Window Position

- LenovoLegionToolkit.Lib/Features/AbstractDriverFeature.cs
Current logging message in VerifyStateSetAsync **always** reports failed verify state, even if the verification actually succeeds.
> Fix logging message in VerifyStateSetAsync

- InnoDependencies/install_dotnet.iss
dotnet is migrating installer's download URLs (https://github.com/dotnet/announcements/issues/336), while it doesn't impact the current download URL but it's a good time to update to new URLs and patch version.
Feel free to close it if this is not needed.
> Update dotnet runtime version and links

- LenovoLegionToolkit.Lib/Features/RefreshRateFeature.cs
- LenovoLegionToolkit.Lib/Features/ResolutionFeature.cs
- LenovoLegionToolkit.Lib/System/InternalDisplay.cs
Using display path APIs instead of `display.SetSettings()` to change internal display refresh rate has a measurable improvement in battery life.
Using `display.SetSettings()` to change to 60Hz: 8.33W battery drain (Active signal mode unchanged)
Using display path APIs to change to 60Hz: 7.24W battery drain (Active signal mode changed to 60Hz)
Related to closed issue #1325, but this time I decided to implement this change myself instead of making another issue.
> Use display path APIs to change internal display settings, for better 60Hz battery life

- LenovoLegionToolkit.Lib/NativeMethods.txt
- LenovoLegionToolkit.Lib/Settings/ApplicationSettings.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Utils/NotificationsManager.cs
- LenovoLegionToolkit.WPF/Windows/Settings/NotificationsSettingsWindow.xaml
- LenovoLegionToolkit.WPF/Windows/Settings/NotificationsSettingsWindow.xaml.cs
- LenovoLegionToolkit.WPF/Windows/Utils/INotificationWindow.cs
- LenovoLegionToolkit.WPF/Windows/Utils/NativeLayeredWindow.cs
- LenovoLegionToolkit.WPF/Windows/Utils/NotificationAoTWindow.cs
- LenovoLegionToolkit.WPF/Windows/Utils/NotificationWindow.cs
Closes: #980.
References: #1053.
Replace: #1349.
Create a C#-implementated AoT OSD window.
The implementation borrows heavily from [g-helper](https://github.com/seerge/g-helper)'s [OSDNativeForm](https://github.com/seerge/g-helper/blob/main/app/Helpers/OSDBase.cs). I changed some things in order to make it more suitable for LLT.
Basically the `NotificationAoTWindow` is only a bitmap carrier. We need to create a bitmap view of a WPF notification window, and then transfer it to the carrier. The problem I had months ago was, I didn't find a way to get the bitmap view without showing the window in foreground. I'm working on it and hope will get a solution soon.
Status update: It seems to only be possible to render the `_mainGrid` element in memory (without showing it). But that's not enough - …
> Notifications Always on Top (AoT)

- LenovoLegionToolkit.Lib/Extensions/DisplayExtensions.cs
Minor update to #1647 where the pathInfos array is edited in-place instead of creating a new array.
Used a for loop instead of `FindIndex()` because I'm not confident enough in winapi to know if there can only be one `PathInfo` per `PathDisplaySource` or not
> Edit the pathInfos array in-place instead of creating a new one.

- LenovoLegionToolkit.Lib/IoCModule.cs
- LenovoLegionToolkit.Lib/Services/BatteryDischargeRateMonitorService.cs
- LenovoLegionToolkit.Lib/Structs.cs
- LenovoLegionToolkit.Lib/System/Battery.cs
- LenovoLegionToolkit.WPF/App.xaml.cs
- LenovoLegionToolkit.WPF/Pages/BatteryPage.xaml
- LenovoLegionToolkit.WPF/Pages/BatteryPage.xaml.cs
- LenovoLegionToolkit.WPF/Resources/Resource.Designer.cs
- LenovoLegionToolkit.WPF/Resources/Resource.resx
- LenovoLegionToolkit.WPF/Resources/Resource.vi.resx
- LenovoLegionToolkit.WPF/Windows/Utils/StatusWindow.xaml
- LenovoLegionToolkit.WPF/Windows/Utils/StatusWindow.xaml.cs
Added features:
- Battery wear level, min and max discharge rate.
- Updates the BatteryInformation struct and logic to track and display these new metrics.
- Modifies the UI (BatteryPage.xaml, StatusWindow) to show minimum/maximum discharge rates and wear level.
- Add localization for Vietnamese.
Personally, I do monitor battery when off the wall a lots, so these changes would save me few steps from calculating them on my own.
> Add battery min/max discharge rate and wear level
